version: '3'

services:

  api:
    build: .
    image: githunter-api:1.0
    restart: always
    environment:
      GH_LOG_LEVEL: debug
      GH_GRAPHQL_GITHUB_URL: https://api.github.com/graphql
      GH_GRAPHQL_GITLAB_URL: https://gitlab.com/api/graphql
      GH_SERVER_PORT: 3001
    ports:
      - 3001:3001
